config/routes.rb
Rails.application.routes.draw do

  resources :fields
  resources :articles do
	resources :comments
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/field.rb
class Field < ActiveRecord::Base
  self.rgeo_factory_generator = RGeo::Geos.factory_generator
  set_rgeo_factory_for_column(:shape, RGeo::Geographic.spherical_factory(:srid => 4326))
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	http_basic_authenticate_with name: "vika", password: "vika", except: [:index, :show]
	
	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def show
 		 @article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
  		@article = Article.find(params[:id])
 
 		 if @article.update(article_params)
   			 redirect_to @article
 		 else
   			 render 'edit'
 		 end
	end

	def destroy
  		@article = Article.find(params[:id])
 		@article.destroy
 
 		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :text)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy	

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController

  def index
    @fields = Field.all
  end

  def new
    @fields = Field.new
  end

  def create
    @field = Field.new(field_params)
    #@field = Field.new({id: '1', name:'1', shape:"MULTIPOLYGON((1.7162916854424444 103.45203161621089, 1.4678221588572677 103.42868566894526, 1.2509033734229906 103.75003576660151, 1.6682474647616954 104.06726599121089, 1.7162916854424444 103.45203161621089))"})

    if @field.save
      redirect_to @field
    else
      render 'new'
    end
  end

  def show
    @field = Field.find(params[:id])
    @shape = RGeo::GeoJSON.encode(@field[:shape])
  end

  def edit
    @field = Field.find(params[:id])
  end

  def update
    @field = Field.find(params[:id])

    if @field.update(field_params)
      redirect_to @field
    else
      render 'edit'
    end
  end

  def destroy
    @field = Field.find(params[:id])
    @field.destroy

    redirect_to fields_path
  end

  private
  def field_params
    params.require(:field).permit(:name, :shape)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back to Articles', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/fields/_form.html.erb
<%= form_for :field, url: fields_path do |f| %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :shape %><br>
      <%= f.text_field :shape %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/fields/edit.html.erb
<h1>Edit Field</h1>

<%= render 'form' %>

<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<h1>Listing Fields</h1>
<%= link_to 'New field', new_field_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Shape</th>
    <th colspan="3"></th>
  </tr>

  <% @fields.each do |field| %>
      <tr>
        <td><%= field.name %></td>
        <td><%= field.shape %></td>
        <td><%= link_to 'Show', field_path(field) %></td>
        <td><%= link_to 'Edit', edit_field_path(field) %></td>
        <td><%= link_to 'Destroy', field_path(field),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/fields/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @field.name %>
</p>

<p>

  <strong>Shape:</strong>
  <%= @field.shape %>
</p>

<style>#map { height: 180px; }</style>
<div id="map"></div>
<script>
$(document).ready(function(){
    var map = L.map('map', {
        center: [0.8, 100.9],
        zoom: 8
    });
    new L.GeoJSON(<%=raw @shape.to_json()%>, {
        style: function(feature) {
            return feature.properties.style
        }
    }).addTo(map);
    //var map = L.map('map').setView([[-41.2858, 174.78682], 14]);
    //var multipolygon = L.multiPolygon(<%=raw @shape.to_json()%>).addTo(map)
    //var geo_json = L.geoJson(<%=raw @shape.to_json()%>);
    //var multipolygon = L.multiPolygon(geo_json).addTo(map);

});

</script>

<%= link_to 'Edit Field', edit_field_path(@field) %> |
<%= link_to 'Back to Fields', fields_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<p>
<%= link_to 'My Blog', controller: 'articles' %>
</p>
<p>
<%= link_to 'Fields', controller: 'fields' %>
</p>